export const MESSAGE_TO_CLIENT = 'MESSAGE_TO_CLIENT'
export const MESSAGE_TO_SERVICE = 'MESSAGE_TO_SERVICE'
export const APPOINTMENT_TO_SERVICE = 'APPOINTMENT_TO_SERVICE'
export const REVIEW_TO_SERVICE = 'REVIEW_TO_SERVICE'
